ORIGINAL_TILE_SIZE: int = 16
SCALE: int = 3
TILE_SIZE: int = ORIGINAL_TILE_SIZE * SCALE

MAX_SCREEN_COL: int = 16
MAX_SCREEN_ROW: int = 12

SCREEN_WIDTH: int = TILE_SIZE * MAX_SCREEN_COL
SCREEN_HEIGHT: int = TILE_SIZE * MAX_SCREEN_ROW

FPS: int = 60

BACKGROUND_COLOR: tuple[int, int, int] = (0, 0, 0)

WINDOW_TITLE: str = "java-rpg"

PLAYER_SPEED: float = 180.0

WALK_ANIMATION_INTERVAL: float = 14.0 / 60.0
